"""Initial migration

Revision ID: 4cc0f35b3a19
Revises: 
Create Date: 2024-11-07 13:15:30.938190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision: str = '4cc0f35b3a19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcel_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_parcel_types_id'), 'parcel_types', ['id'], unique=False)
    op.create_table('parcels',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('user_session_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('parcel_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_type_id'], ['parcel_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcels_name'), 'parcels', ['name'], unique=False)
    op.create_index(op.f('ix_parcels_user_session_id'), 'parcels', ['user_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcels_user_session_id'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_name'), table_name='parcels')
    op.drop_table('parcels')
    op.drop_index(op.f('ix_parcel_types_id'), table_name='parcel_types')
    op.drop_table('parcel_types')
    # ### end Alembic commands ###
